CREATE TABLE public.book
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userName varchar(100) NOT NULL,
	email varchar(100) NOT NULL,
	homepage varchar(300),
	text varchar(1000) NOT NULL,
	datePublish timestamp with time zone NOT NULL,
	ip char(50) NOT NULL,
	browser varchar(300) NOT NULL
);